version: "3.9"

services:
  hub_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app:delegated
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
    command: uvicorn apps.hub_server.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app/apps
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
